spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

supabase:
  jwks:
    url: https://grcteqamjdtvgclhvxcm.supabase.co/auth/v1/keys
  api:
    key: ${SUPABASE_ANON_KEY}   # replace with actual anon key from Supabase