spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/influencer_marketplace}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:devpass}
supabase:
  jwt:
    issuer: ${SUPABASE_ISSUER:https://grcteqamjdtvgclhvxcm.supabase.co/auth/v1}
    secret: ${SUPABASE_JWT_SECRET:2UWpGAoXJ538/VTrl0sSxz7ON9K45ZF2PeeUKkhUZN8gqEulak298Ok1dEmNT3uh9zFI+T8Hz6dEDng4Qmur9A==}